INSERT into role VALUES('1','ADMIN')
INSERT into role VALUES('2','CLIENT')
INSERT into client VALUES('1','3','22','2500','0','admin@gmail.com','0','Unknown','male','5','aesthetics','179','Unknown','0','0','$2a$10$RtMkltHiahk8AJmLZJ4EYOlQZx/S/rJwLDO1Y37p7vWVuJImePk32','0','chest','Admin','95')
INSERT into client_role VALUES('1','1')
INSERT into exercises VALUES('1','Pull up bar','Pull ups','Lats/Rhomboids','Biceps','Pull day 1/Pull day 2/ExtraBack','1')
INSERT into Exercises VALUES('39','Dip station','Dips','Chest','Triceps','Push day 1/Push day 2/ExtraChest/ExtraArms','1')
INSERT into Exercises VALUES('2','Hyperextension bench','Back extensions','Erectors','Glutes','Pull day 1/ExtraBack','1')
INSERT into Exercises VALUES('4','Flat surface','Push ups','Chest','Triceps', 'ExtraChest','1')
INSERT into Exercises VALUES('5','Flat bench and barbell','Barbell bench press','(lower)Chest','Triceps','Push day 1/Push day 2','1')
INSERT into Exercises VALUES('6','Incline bench and barbell','Barbell incline bench press','(upper)Chest','Triceps','Push day 1/Push day 2','1')
INSERT into Exercises VALUES('7','Flat bench and dumbbells','Dumbbell bench press','(lower)Chest','Triceps','N/A','1')
INSERT into Exercises VALUES('8','Incline bench and dumbbells','Dumbbell incline bench press','(upper)Chest','Triceps','N/A','1')
INSERT into Exercises VALUES('9','Barbell','Yates row','Upper back','Biceps','Pull day 2','1')
INSERT into Exercises VALUES('10','Barbell','Deadlift','Lower back','Hamstrings','Pull day 1','1')
INSERT into Exercises VALUES('11','Barbell','Rack pulls','Lower back','Traps', 'Pull day 1','1')
INSERT into Exercises VALUES('12','Lat pull down machine and wide bar attachment','Lat pull down (wide)','Upper back','Biceps', 'Pull day 1/Pull day 2','1')
INSERT into Exercises VALUES('13','Lat pull down machine and v-bar attachment','Lat pull down (neutral)','Upper back','Biceps','Pull day 1/Pull day 2','1')
INSERT into Exercises VALUES('14','Lat pull down machine and bar attachment','Lat pull down (reverse)','Upper back','Biceps', 'Pull day 1/Pull day 2','1')
INSERT into Exercises VALUES('15','Barbell v-bar grip','T-bar rows','Upper back','Erectors', 'N/A','1')
INSERT into Exercises VALUES('16','Pec-deck machine','Machine fly','Lower chest','Upper chest', 'Push day 2','1')
INSERT into Exercises VALUES('17','Flat bench and dumbbells','In and Outs','Lower chest','Triceps','Push day 1/Push day 2','1')
INSERT into Exercises VALUES('18','Dumbbells','Arnold press','Delts','Triceps', 'N/A','1')
INSERT into Exercises VALUES('19','Cable tower and handle attachment','Cable side laterals','Side delts','Traps','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('20','Cable tower and rope attachment','Face pulls','Rear delts','Traps','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('21','Dumbbells','Skull crushers','Triceps','Delts','Push day 2','1')
INSERT into Exercises VALUES('22','Incline bench and dumbbells','Bench assisted rows','Upper back','Biceps','N/A','1')
INSERT into Exercises VALUES('23','Preacher curl bench and EZ curl bar','Preacher curls','Biceps','Forearms','Pull day 2','1')
INSERT into Exercises VALUES('24','Barbell/EZ curl bar','Slow negative curls','Biceps','Forearms','Pull day 1','1')
INSERT into Exercises VALUES('25','Dumbbells','Dumbbell shrugs','Traps','Forearms','N/A','1')
INSERT into Exercises VALUES('26','Barbell','Overhead barbell shrugs','Traps','Core','N/A','1')
INSERT into Exercises VALUES('27','Squat rack and barbell','Back squats','Legs','Core','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('28','Hip adductor machine','Hip adductor stretch','Adductor','Glutes','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('29','Hip abductor machine','Hip abductor stretch','Abductor','Glutes','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('30','Leg press machine','Leg press','Legs','Core','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('31','Hamstring curl machine','Hamstring curls','Hamstrings','Calves','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('32','Barbell/Smith machine','Weighted standing lunges','Legs','Core','Leg day 1/ExtraLegs','1')
INSERT into Exercises VALUES('33','Squat rack and barbell','Overhead press','Delts','Triceps','Pull day 2','1')
INSERT into Exercises VALUES('34','Pec-deck machine','Reverse machine fly','Rear delt','Triceps','Pull day 1','1')
INSERT into Exercises VALUES('35','Incline bench and dumbbells','Bench assisted rear delt fly','Rear delts','Triceps','Pull day 2','1')
INSERT into Exercises VALUES('36','Dumbbells','Dumbbell lateral raises','Side delt','Traps','Pull day 1/Pull day 2/ExtraDelts','1')
INSERT into Exercises VALUES('37','Pec-deck machine','Reverse machine fly','Rear delt','Triceps','N/A','1')
INSERT into Exercises VALUES('38','Cable tower with handle attachments','Cable flys','Chest','Triceps','Push day 1','1')
INSERT into Exercises VALUES('3','Cable tower with rope attachment','Tricep pull down','Triceps','Anconeus','Push day 1/Push day 2','1')
INSERT into Exercises VALUES('40','Cable tower with rope attachment','Overhead tricep extension','Triceps','Triceps','Push day 1/Push day 2','1' )
INSERT into Exercises VALUES('41','Micro plates','Shoulder warm up','Delts','Delts','Push day 1/Push day 2','1')
INSERT into Exercises VALUES('42','Bench and barbell','Close grip bench','Triceps','Chest','Push day 1','1')
INSERT into Exercises VALUES('43','Dumbbells','Hammer curl','Bicep','Brachialis','Pull day 1','1')
INSERT into Exercises VALUES('44','Dumbbells','Conventional curl','Bicep','Brachialis','N/A','1')
INSERT into Exercises VALUES('45','Barbell/EZ curl bar','Reverse curl','Bicep','Forearms','Pull day 1','1')
INSERT into Exercises VALUES('46','Calf raise machine/Barbell and raised platform','Calf raises','Calves','Hamstrings','Leg day 1/Leg day 2','1')
INSERT into Exercises VALUES('47','Dumbbells','Floor flies','Chest','Triceps','Push day 2','1')
INSERT into Exercises VALUES('48','Cable tower with straight bar attachment','Straight arm lat push down','Lats','Triceps','Pull day 2','1')
INSERT into Exercises VALUES('49','Cable tower with straight bar attachment','Cable curl','Biceps','Forearms','Pull day 2','1')
INSERT into Exercises VALUES('50','Cable tower with straight bar attachment','Reverse cable curl','Biceps','Forearms','Pull day 2','1')
INSERT into Exercises VALUES('51','Dumbbell','Goblet squats','Hamstrings','Glutes','Leg day 2/ExtraLegs','1')
INSERT into Exercises VALUES('52','Barbell','Stiff leg deadlift','Hamstrings','Glutes','Leg day 2','1')
INSERT into exercises VALUES('53','Pull up bar','Chin ups','Arms','Back','ExtraArms','1')
INSERT into Exercises VALUES('54','Barbell','Weighted walking lunges','Legs','Core','Leg day 1','1')
INSERT into Exercises VALUES('55','Dumbbells','Front raises','Front delts','Triceps','ExtraDelts','1')
INSERT into Exercises VALUES('56','Dumbbells','Bent over rear delt flies','Rear delts','Back','ExtraDelts','1')
INSERT into Exercises VALUES('57','Cable tower with rope attachment','Cable crunch','Abs','Core','ExtraAbs','1')
INSERT into Exercises VALUES('58','Decline bench','Bench assisted dragonflies','Abs','Core','ExtraAbs','1')
INSERT into Exercises VALUES('59','Pull up bar','Hanging leg raises','Abs','Core','ExtraAbs','1')
INSERT into Client_Exercises_Used VALUES(1,1)
INSERT into Client_Exercises_Used VALUES(1,2)
INSERT into Client_Exercises_Used VALUES(1,3)
INSERT into Client_Exercises_Used VALUES(1,4)
INSERT into Client_Exercises_Used VALUES(1,5)
INSERT into Client_Exercises_Used VALUES(1,6)
INSERT into Client_Exercises_Used VALUES(1,7)
INSERT into Client_Exercises_Used VALUES(1,8)
INSERT into Client_Exercises_Used VALUES(1,9)
INSERT into Client_Exercises_Used VALUES(1,10)
INSERT into Client_Exercises_Used VALUES(1,11)
INSERT into Client_Exercises_Used VALUES(1,12)
INSERT into Client_Exercises_Used VALUES(1,13)
INSERT into Client_Exercises_Used VALUES(1,14)
INSERT into Client_Exercises_Used VALUES(1,15)
INSERT into Client_Exercises_Used VALUES(1,16)
INSERT into Client_Exercises_Used VALUES(1,17)
INSERT into Client_Exercises_Used VALUES(1,18)
INSERT into Client_Exercises_Used VALUES(1,19)
INSERT into Client_Exercises_Used VALUES(1,20)
INSERT into Client_Exercises_Used VALUES(1,21)
INSERT into Client_Exercises_Used VALUES(1,22)
INSERT into Client_Exercises_Used VALUES(1,23)
INSERT into Client_Exercises_Used VALUES(1,24)
INSERT into Client_Exercises_Used VALUES(1,25)
INSERT into Client_Exercises_Used VALUES(1,26)
INSERT into Client_Exercises_Used VALUES(1,27)
INSERT into Client_Exercises_Used VALUES(1,28)
INSERT into Client_Exercises_Used VALUES(1,29)
INSERT into Client_Exercises_Used VALUES(1,30)
INSERT into Client_Exercises_Used VALUES(1,31)
INSERT into Client_Exercises_Used VALUES(1,32)
INSERT into Client_Exercises_Used VALUES(1,33)
INSERT into Client_Exercises_Used VALUES(1,34)
INSERT into Client_Exercises_Used VALUES(1,35)
INSERT into Client_Exercises_Used VALUES(1,36)
INSERT into Client_Exercises_Used VALUES(1,37)
INSERT into Client_Exercises_Used VALUES(1,38)
INSERT into Client_Exercises_Used VALUES(1,39)
INSERT into Client_Exercises_Used VALUES(1,40)
INSERT into Client_Exercises_Used VALUES(1,41)
INSERT into Client_Exercises_Used VALUES(1,42)
INSERT into Client_Exercises_Used VALUES(1,43)
INSERT into Client_Exercises_Used VALUES(1,44)
INSERT into Client_Exercises_Used VALUES(1,45)
INSERT into Client_Exercises_Used VALUES(1,46)
INSERT into Client_Exercises_Used VALUES(1,47)
INSERT into Client_Exercises_Used VALUES(1,48)
INSERT into Client_Exercises_Used VALUES(1,49)
INSERT into Client_Exercises_Used VALUES(1,50)
INSERT into Client_Exercises_Used VALUES(1,51)
INSERT into Client_Exercises_Used VALUES(1,52)
INSERT into Client_Exercises_Used VALUES(1,53)
INSERT into Client_Exercises_Used VALUES(1,54)
INSERT into Client_Exercises_Used VALUES(1,55)
INSERT into Client_Exercises_Used VALUES(1,56)
INSERT into Client_Exercises_Used VALUES(1,57)
INSERT into Client_Exercises_Used VALUES(1,58)
INSERT into Client_Exercises_Used VALUES(1,59)






















